### PR TITLE
Initial Governing Documents

### PR DESCRIPTION
**Pull request by pcunning**
This PR will serve as the discussion around our initial governing documents.

### CODE REVIEW

**Comment by connerk** [comment]
@pcunning what do you think we should do with these docs, considering our organizational changes?

**Comment by pcunning** [comment]
Does not hurt to keep them here...

**Comment by connerk** [comment]
should they be updated to reflect our actual intent?

**Comment by pcunning** [comment]
They are a work in progress and not adopted, you are welcome to update them or hold discussion on how the should be updated here.

**Pull request closed without merging**
